---
# vars file for roles/installAWS
 ami_id: ami-0470e33cd681b2476
 region: ap-south-1
 keypair: LocalKP
 security_group: ElasticSearchSG
 user_data: |
            #!/bin/bash
            sudo yum update -y
            sudo yum -y install java-1.8.0-openjdk
            sudo rpm -i https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-x86_64.rpm
 tag_name: ElasticsearchNodes
