---
# tasks file for roles/forES
 - name: Setting Private IPs of all three nodes
   set_fact:
        master_priIP: "{{ ec2.instances[0].private_ip }}"
        node1_priIP: "{{ ec2.instances[1].private_ip }}"
        node2_priIP: "{{ ec2.instances[2].private_ip }}"


 - name: Add new instances to host group
   template:
      src: templates/hosts.j2
      dest: /etc/ansible/hosts
   delegate_to: localhost

 - name: Add elasticsearch.yml for master
   template:
       src: templates/elasticsearch_master.yml.j2
       dest: /etc/ansible/elasticsearch_m.yml.j2
   delegate_to: localhost

 - name: Add elasticsearch.yml for node1
   template:
      src: templates/elasticsearch_node1.yml.j2
      dest: /etc/ansible/elasticsearch_n1.yml.j2

 - name: Add elasticsearch.yml for node2
   template: 
      src: templates/elasticsearch_node2.yml.j2 
      dest: /etc/ansible/elasticsearch_n2.yml.j2
   delegate_to: localhost     
